from flask import Flask, render_template, request, make_response
from vaccines import get_schedule
import io
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle 
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.units import inch

app = Flask(__name__)

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/about')
def about():
    return render_template('about.html')

@app.route('/stats')
def stats():
    return render_template('stats.html')

@app.route('/scheduler')
def scheduler():
    return render_template('scheduler.html')

@app.route('/result', methods=['POST'])
def result():
    child_name = request.form.get('child_name', 'Your Child')
    age_years = int(request.form.get('age_years', 0) or 0)
    age_months_extra = int(request.form.get('age_months_extra', 0) or 0)
    age_months = (age_years * 12) + age_months_extra
    vaccines_input = request.form.get('vaccines_received', '')
    if vaccines_input.strip() == '':
        vaccines_received = []
    else:
        vaccines_received = [v.strip() for v in vaccines_input.split(',')]
    done, overdue, upcoming = get_schedule(age_months, vaccines_received)
    return render_template('result.html',
        child_name=child_name,
        age_months=age_months,
        done=done,
        overdue=overdue,
        upcoming=upcoming
    )

@app.route('/download-pdf', methods=['POST'])
def download_pdf():
    child_name = request.form.get('child_name', 'Your Child')
    age_months = int(request.form.get('age_months', 0))
    vaccines_input = request.form.get('vaccines_received', '')
    if vaccines_input.strip() == '':
        vaccines_received = []
    else:
        vaccines_received = [v.strip() for v in vaccines_input.split(',')]

    done, overdue, upcoming = get_schedule(age_months, vaccines_received)

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                            rightMargin=inch, leftMargin=inch,
                            topMargin=inch, bottomMargin=inch)

    story = []

    title_style = ParagraphStyle('title', fontSize=24, fontName='Helvetica-Bold',
                                  textColor=colors.HexColor('#042C53'), spaceAfter=6)
    story.append(Paragraph("DoseWise", title_style))

    sub_style = ParagraphStyle('sub', fontSize=12, fontName='Helvetica',
                                textColor=colors.HexColor('#5a7a9a'), spaceAfter=4)
    story.append(Paragraph("WHO-Standard Vaccination Schedule", sub_style))
    story.append(Spacer(1, 0.2*inch))

    info_style = ParagraphStyle('info', fontSize=14, fontName='Helvetica-Bold',
                                 textColor=colors.HexColor('#1a2a3a'), spaceAfter=4)
    story.append(Paragraph(f"Child: {child_name}", info_style))
    story.append(Paragraph(f"Age: {age_months} months ({age_months // 12} years {age_months % 12} months)", info_style))
    story.append(Spacer(1, 0.3*inch))

    item_style = ParagraphStyle('item', fontSize=11, fontName='Helvetica',
                                 leftIndent=20, spaceAfter=4)

    if overdue:
        s = ParagraphStyle('od', fontSize=14, fontName='Helvetica-Bold',
                           textColor=colors.HexColor('#e53e3e'), spaceAfter=8)
        story.append(Paragraph(f"OVERDUE Vaccines ({len(overdue)})", s))
        for v in overdue:
            story.append(Paragraph(f"- {v['name']} -- {v['description']} (Was due at {v['due_age']} months)", item_style))
        story.append(Spacer(1, 0.2*inch))

    if upcoming:
        s = ParagraphStyle('up', fontSize=14, fontName='Helvetica-Bold',
                           textColor=colors.HexColor('#0C447C'), spaceAfter=8)
        story.append(Paragraph(f"UPCOMING Vaccines ({len(upcoming)})", s))
        for v in upcoming:
            story.append(Paragraph(f"- {v['name']} -- {v['description']} (Due at {v['due_age']} months)", item_style))
        story.append(Spacer(1, 0.2*inch))

    if done:
        s = ParagraphStyle('dn', fontSize=14, fontName='Helvetica-Bold',
                           textColor=colors.HexColor('#38a169'), spaceAfter=8)
        story.append(Paragraph(f"COMPLETED Vaccines ({len(done)})", s))
        for v in done:
            story.append(Paragraph(f"- {v['name']} -- {v['description']}", item_style))
        story.append(Spacer(1, 0.2*inch))

    footer_style = ParagraphStyle('footer', fontSize=9, fontName='Helvetica',
                                   textColor=colors.HexColor('#888'), spaceBefore=20)
    story.append(Paragraph("Generated by DoseWise -- GNEC Hackathon 2026 -- SDG 3: Good Health & Well-being", footer_style))

    doc.build(story)
    buffer.seek(0)

    response = make_response(buffer.read())
    response.headers['Content-Type'] = 'application/pdf'
    response.headers['Content-Disposition'] = f'attachment; filename=DoseWise_{child_name}_Schedule.pdf'
    return response

if __name__ == '__main__':
    app.run(debug=True)